/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador;

import java.util.Enumeration;
import java.util.Hashtable;

/**
 *
 * @author Arnel
 */
public class tabla_simbolos extends javax.swing.JFrame {

    /**
     * Creates new form tabla_simbolos
     */
//    public tabla_simbolos() {
//        initComponents();
//        llenartabla();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLexico = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaLexico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Longitud", "Valor", "Indice"
            }
        ));
        jScrollPane1.setViewportView(TablaLexico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    
//    private void llenartabla(){
//    a_lexico lexico2 = new a_lexico();
////        Hashtable tabla2 = lexico2.tabla();
//        Enumeration<a_lexico.Tokens> nombres = tabla2.elements();
//        Enumeration<Integer> claves = tabla2.keys();
//        a_lexico.Tokens auxiliar;
//        int tam = tabla2.size(), contador = 0;
//        String token[][] = new String[tam][5];
//        String token2[][] = new String[tam][5];
//        while (nombres.hasMoreElements()) {
//            auxiliar = nombres.nextElement();
//            int llave = claves.nextElement();
//            int clave = auxiliar.clave;
//            String palabra = auxiliar.palabra;
//            String descripcion = auxiliar.descripcion;
//            token[contador][4] = "" + llave;
//            token[contador][3] = "Id " + clave;
//            token[contador][0] = "" + palabra;
//            token[contador][1] = "" + descripcion;
//            token[contador][2] = "" + palabra.length();
//            if(clave<=0){
//                token[contador][1]="Error";
//            }
//            contador++;
//        }
//        for (int i = 0; i < tam; i++) {
//            for (int j = 0; j < 5; j++) {
//                token2[tam-1-i][j] = token[i][j];
//            }
//        }
//        
//        for (int i = 0; i < tam; i++) {
//            for (int j = 0; j < 5; j++) {
//                TablaLexico.setValueAt(token2[i][j], i,j);
//            }
//        }
//}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabla_simbolos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabla_simbolos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabla_simbolos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabla_simbolos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabla_simbolos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaLexico;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
